version: '3.8'

services:

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

#  pgadmin:
#    image: dpage/pgadmin4
#    restart: always
#    container_name: pgadmin
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
#    ports:
#      - '5050:80'
#    depends_on:
#      - postgres

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
#  app:
#    container_name: app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '5000:5000'
#    depends_on:
#      postgres:
#        condition: service_healthy
#    env_file:
#      - .env
#    volumes:
#      - ./src:/app/src
#    command: npx prisma migrate dev
#    restart: always

volumes:
  postgres: